name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'The repository authentication token'
    required: true
  label_review:
    description: 'The label that triggers review requests'
    required: true
  reviewer_number:
    description: 'The number of reviewers assigned to a pull request'
    required: true
  approval_number:
    description: 'The number of approvals required to be accepted'
    required: true
  permanent_reviewer:
    description: 'The collaborator assigned by default on pull requests'
    required: true
runs:
  using: 'node12'
  main: 'index.js'