name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  label_review:
    description: 'The label that triggers review requests'
    required: true
    default: 'RFR'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'