on:
  pull_request:
    types: [labeled]
  pull_request_review:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: pull request workflow
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label_test: 'RFT'
          label_review: 'RFR'
          label_changes_requested: 'FFF'
          label_approved: 'RTM'
          label_emergency: 'MGY'
          permanent_reviewer: mathieumuller
          mergeator: neime
          reviewers_number: 3
          approvals_number: 2
