name: Node Alpine Slim

on:
  push:
    paths:
      - 'node-alpine-slim/*'
      - '.github/workflows/node-alpine-slim.yml'

jobs:

  build:

    name: Build docker image (with cache) and push it to registry
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - uses: whoan/docker-build-with-cache-action@master
      with:
        push_image_and_stages: false
