name: Pull request worklow
on:
  pull_request:
    types: [labeled]

jobs:
  uppler-pr-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request workflow
        uses: mathieumuller/uppler-pr-workflow@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERMANENT_REVIEWER: "adpauly"
          FINAL_REVIEWER: "adpauly"
          AVAILABLE_REVIEWERS: [neime, mathieumuller]