name: Pull request worklow
on:
  pull_request:
    types: [labeled]
  pull_request_review:

jobs:
  uppler-pr-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PERMANENT_REVIEWER: "adpauly"
           FINAL_REVIEWER: "neime"
           AVAILABLE_REVIEWERS: "neime adpauly mathieu-uppler"
        with:
          script: |
            console.log(`${process.env.GITHUB_WORKSPACE}`);
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/approval.js`)
            script({github, context})
    
