name: Pull request worklow
on:
  pull_request:
    types: [labeled]

jobs:
  pull-request-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Pull request workflow
        uses: mathieumuller/pull-request-workflow@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERMANENT_REVIEWER: "@adpauly"